# Generated by Django 5.2.9 on 2025-12-03 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('CSE', 'ЦСЭ'), ('NIKA', 'NIKA')], default='CSE', max_length=10, verbose_name='Тип реестра (Организация)')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Наименование организации')),
                ('registration_number', models.CharField(max_length=50, verbose_name='УНП (Registration Number)')),
                ('title', models.CharField(max_length=255, verbose_name='Название семинара')),
                ('program', models.TextField(verbose_name='Программа семинара')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Семинар',
                'verbose_name_plural': 'Семинары',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО участника')),
                ('order_number', models.PositiveIntegerField(help_text='Целое число, уникальное в рамках семинара', verbose_name='Порядковый номер')),
                ('certificate_number', models.CharField(blank=True, max_length=50, verbose_name='Сгенерированный номер')),
                ('file_print', models.ImageField(blank=True, null=True, upload_to='certificates/print/', verbose_name='Файл для печати')),
                ('file_web', models.ImageField(blank=True, null=True, upload_to='certificates/web/', verbose_name='Файл для веб')),
                ('manual_upload', models.ImageField(blank=True, null=True, upload_to='certificates/manual/', verbose_name='Ручная загрузка (Скан)')),
                ('seminar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.seminar', verbose_name='Семинар')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'unique_together': {('seminar', 'order_number')},
            },
        ),
    ]
