# Generated by Django 5.2.9 on 2025-12-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_print',
            field=models.FileField(blank=True, null=True, upload_to='certificates/print/', verbose_name='Файл для печати (PDF)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_web',
            field=models.FileField(blank=True, null=True, upload_to='certificates/web/', verbose_name='Файл для веб (PDF)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='manual_upload',
            field=models.FileField(blank=True, null=True, upload_to='certificates/manual/', verbose_name='Ручная загрузка'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='order_number',
            field=models.PositiveIntegerField(verbose_name='Порядковый номер'),
        ),
    ]
