# Generated by Django 5.2.9 on 2025-12-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_seminar_options_alter_certificate_file_print_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seminar',
            options={'verbose_name': 'Семинар', 'verbose_name_plural': 'Семинары'},
        ),
    ]
