# Generated by Django 5.2.9 on 2025-12-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seminar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Порядковый номер'),
        ),
    ]
