# Generated by Django 5.2.9 on 2025-12-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_certificate_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/previews/', verbose_name='JPG Превью (Для сайта)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_print',
            field=models.FileField(blank=True, null=True, upload_to='certificates/print/', verbose_name='PDF для печати (Без печати)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='file_web',
            field=models.FileField(blank=True, null=True, upload_to='certificates/web/', verbose_name='PDF для клиента (С печатью)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='manual_upload',
            field=models.FileField(blank=True, null=True, upload_to='certificates/manual/', verbose_name='Ручная загрузка (Скан)'),
        ),
    ]
