# Generated by Django 5.2.9 on 2025-12-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certificate_preview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(max_length=138, verbose_name='Название семинара'),
        ),
    ]
