# Generated by Django 5.2.9 on 2025-12-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_seminar_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(max_length=142, verbose_name='Название семинара'),
        ),
    ]
