# Generated by Django 5.2.9 on 2025-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_seminar_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название семинара'),
        ),
    ]
