"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.9.
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = 'RENDER' not in os.environ

ALLOWED_HOSTS = ["*"]

# FIX FOR RENDER: Доверяем запросам с домена Render (для CSRF)
# Замени на свой реальный адрес, если он другой
CSRF_TRUSTED_ORIGINS = [
    'https://registry-export-assistance-center.onrender.com', 
]

# Application definition

INSTALLED_APPS = [
    # Standard apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'storages',  # Для работы с S3 (Supabase Storage)
    
    # My apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # WhiteNoise для статики
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# Uses Supabase (PostgreSQL) on Render/Local via .env (DATABASE_URL)
DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
LANGUAGE_CODE = 'ru'
TIME_ZONE = 'Europe/Minsk'
USE_I18N = True
USE_TZ = True

# --- STATIC FILES (CSS, JS) ---
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# --- MEDIA FILES (Supabase Storage via S3) ---

# Берем настройки из переменных окружения
AWS_ACCESS_KEY_ID = os.environ.get('SUPABASE_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('SUPABASE_SECRET_ACCESS_KEY')
AWS_S3_ENDPOINT_URL = os.environ.get('SUPABASE_ENDPOINT_URL')
AWS_STORAGE_BUCKET_NAME = 'media' # Имя бакета в Supabase (должен быть создан!)
AWS_S3_REGION_NAME = 'eu-central-1' # Регион бакета (обычно Frankfurt для Supabase)
AWS_DEFAULT_ACL = 'public-read' # Файлы доступны для чтения всем
AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
AWS_QUERYSTRING_AUTH = False # Прямые ссылки без временных токенов

# Настраиваем домен для ссылок (чтобы они открывались как прямые URL)
# Ссылка будет вида: https://<project_id>.supabase.co/storage/v1/object/public/media/
if AWS_S3_ENDPOINT_URL:
    try:
        # Извлекаем project_id из URL (https://<project_id>.supabase.co...)
        _PROJECT_ID = AWS_S3_ENDPOINT_URL.split('https://')[1].split('.')[0]
        AWS_S3_CUSTOM_DOMAIN = f'{_PROJECT_ID}.supabase.co/storage/v1/object/public/{AWS_STORAGE_BUCKET_NAME}'
    except IndexError:
        AWS_S3_CUSTOM_DOMAIN = None

MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/' if AWS_S3_CUSTOM_DOMAIN else '/media/'

# Единая настройка хранилищ (Django 5 Standard)
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'